/**
 * MCP proxy routes — expose MCP tool capabilities via fleet HTTP API.
 *
 * These routes proxy tool calls through the instance's MCP Unix socket,
 * making agent/chat capabilities accessible from the console UI.
 *
 * Most handlers are generated by `mcpProxy` / `mcpWithBody` factories to
 * eliminate boilerplate. The three manual handlers (handleGetScheduled,
 * handleCancelScheduled, handleSearchContacts) retain custom logic for
 * query-param handling and legacy routes.
 */
import type { IncomingMessage, ServerResponse } from 'node:http';
import * as fs from 'node:fs';
import { jsonResponse, requireInstance, parseQueryString, readBody } from '../../lib/http.ts';
import { mcpCall } from '../mcp-client.ts';
import type { FleetDiscovery } from '../discovery.ts';

export interface McpProxyDeps {
  discovery: FleetDiscovery;
}

// ---------------------------------------------------------------------------
// Handler type + factory helpers
// ---------------------------------------------------------------------------

type McpProxyHandler<P extends Record<string, string> = { name: string }> = (
  req: IncomingMessage,
  res: ServerResponse,
  deps: McpProxyDeps,
  params: P,
) => Promise<void>;

interface ProxyOptions {
  timeout?: number;
  successCode?: number;
}

function isJsonObject(value: unknown): value is Record<string, unknown> {
  return value !== null && typeof value === 'object' && !Array.isArray(value);
}

function socketCheck(instance: { socketPath?: string | null }, res: ServerResponse): boolean {
  if (!instance.socketPath || !fs.existsSync(instance.socketPath)) {
    jsonResponse(res, 503, { error: 'MCP socket not available — instance must be running' });
    return false;
  }
  return true;
}

/** Unwrap MCP tool result envelope — extracts JSON from content[0].text if present. */
function unwrapMcpResult(raw: unknown): unknown {
  if (raw && typeof raw === 'object' && 'content' in raw) {
    const content = (raw as { content: unknown[] }).content;
    if (Array.isArray(content) && content.length > 0) {
      const first = content[0] as { type?: string; text?: string };
      if (first.type === 'text' && typeof first.text === 'string') {
        try { return JSON.parse(first.text); } catch { return first.text; }
      }
    }
  }
  return raw;
}

/** Factory for body-less handlers (GET, DELETE, POST without payload). Args derived from path params only. */
function mcpProxy<P extends { name: string }>(
  toolName: string,
  buildArgs?: (params: P) => Record<string, unknown>,
  options?: ProxyOptions,
): McpProxyHandler<P> {
  return async (_req, res, deps, params) => {
    const instance = requireInstance(deps.discovery, params.name, res);
    if (!instance) return;
    if (!socketCheck(instance, res)) return;
    const args = buildArgs ? buildArgs(params) : {};
    const result = await mcpCall(instance.socketPath!, toolName, args, options?.timeout);
    if (result.success) jsonResponse(res, options?.successCode ?? 200, unwrapMcpResult(result.result));
    else jsonResponse(res, 502, { error: result.error ?? 'MCP call failed' });
  };
}

/** Factory for handlers with JSON body — reads body, merges with path params. */
function mcpWithBody<P extends { name: string }>(
  toolName: string,
  buildArgs?: (parsed: Record<string, unknown>, params: P) => Record<string, unknown>,
  options?: ProxyOptions,
): McpProxyHandler<P> {
  return async (req, res, deps, params) => {
    const instance = requireInstance(deps.discovery, params.name, res);
    if (!instance) return;
    if (!socketCheck(instance, res)) return;
    const raw = await readBody(req);
    let parsed: unknown;
    try { parsed = JSON.parse(raw); } catch { jsonResponse(res, 400, { error: 'Invalid JSON body' }); return; }
    if (!isJsonObject(parsed)) {
      jsonResponse(res, 400, { error: 'JSON body must be an object' });
      return;
    }
    const args = buildArgs ? buildArgs(parsed, params) : parsed;
    const result = await mcpCall(instance.socketPath!, toolName, args, options?.timeout);
    if (result.success) jsonResponse(res, options?.successCode ?? 200, unwrapMcpResult(result.result));
    else jsonResponse(res, 502, { error: result.error ?? 'MCP call failed' });
  };
}

// ---------------------------------------------------------------------------
// Scheduled messages
// ---------------------------------------------------------------------------

/** GET /api/lines/:name/scheduled — list scheduled messages; supports ?status= filter. */
export async function handleGetScheduled(
  req: IncomingMessage,
  res: ServerResponse,
  deps: McpProxyDeps,
  params: { name: string },
): Promise<void> {
  const instance = requireInstance(deps.discovery, params.name, res);
  if (!instance) return;
  if (!socketCheck(instance, res)) return;

  const qs = parseQueryString(req.url);
  const args: Record<string, unknown> = {};
  if (qs.status) args.status = qs.status;

  const result = await mcpCall(instance.socketPath!, 'list_scheduled', args);
  if (result.success) jsonResponse(res, 200, unwrapMcpResult(result.result));
  else jsonResponse(res, 502, { error: result.error ?? 'MCP call failed' });
}

// POST /api/lines/:name/scheduled — create a new scheduled message.
export const handleCreateScheduled = mcpWithBody('schedule_message', undefined, { successCode: 201 });

// GET /api/lines/:name/scheduled/:id — get a single scheduled message by ID.
export const handleGetScheduledById = mcpProxy<{ name: string; id: string }>(
  'get_scheduled',
  p => ({ id: parseInt(p.id, 10) }),
);

// PUT /api/lines/:name/scheduled/:id — update a scheduled message.
export const handleUpdateScheduled = mcpWithBody<{ name: string; id: string }>(
  'update_scheduled',
  (body, p) => ({ ...body, id: parseInt(p.id, 10) }),
);

// DELETE /api/lines/:name/scheduled/:id — cancel a scheduled message by path ID.
export const handleCancelScheduledById = mcpProxy<{ name: string; id: string }>(
  'cancel_scheduled',
  p => ({ id: parseInt(p.id, 10) }),
);

/** DELETE /api/lines/:name/scheduled — legacy query-param cancel route. */
export async function handleCancelScheduled(
  req: IncomingMessage,
  res: ServerResponse,
  deps: McpProxyDeps,
  params: { name: string },
): Promise<void> {
  const instance = requireInstance(deps.discovery, params.name, res);
  if (!instance) return;

  const qs = parseQueryString(req.url);
  const messageId = qs.id;
  if (!messageId) {
    jsonResponse(res, 400, { error: 'id query parameter is required' });
    return;
  }

  if (!socketCheck(instance, res)) return;

  const result = await mcpCall(instance.socketPath!, 'cancel_scheduled', { messageId });
  if (result.success) jsonResponse(res, 200, { cancelled: true, messageId });
  else jsonResponse(res, 502, { error: result.error ?? 'MCP call failed' });
}

// ---------------------------------------------------------------------------
// Groups
// ---------------------------------------------------------------------------

// GET /api/lines/:name/groups — list WhatsApp groups for an instance.
export const handleGetGroups = mcpProxy('list_groups', undefined, { timeout: 15_000 });

// GET /api/lines/:name/groups/:jid — get group metadata.
export const handleGetGroupDetail = mcpProxy<{ name: string; jid: string }>(
  'get_group_metadata',
  p => ({ jid: decodeURIComponent(p.jid) }),
  { timeout: 15_000 },
);

// POST /api/lines/:name/groups — create a new group.
export const handleCreateGroup = mcpWithBody('group_create', undefined, { successCode: 201 });

// DELETE /api/lines/:name/groups/:jid — leave a group.
export const handleLeaveGroup = mcpProxy<{ name: string; jid: string }>(
  'group_leave',
  p => ({ id: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/subject — update group subject.
export const handleUpdateGroupSubject = mcpWithBody<{ name: string; jid: string }>(
  'group_update_subject',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/description — update group description.
export const handleUpdateGroupDescription = mcpWithBody<{ name: string; jid: string }>(
  'group_update_description',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// POST /api/lines/:name/groups/:jid/participants — add/remove/promote/demote participants.
export const handleGroupParticipants = mcpWithBody<{ name: string; jid: string }>(
  'group_participants_update',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/settings — update group settings (announcement/locked).
export const handleGroupSettings = mcpWithBody<{ name: string; jid: string }>(
  'group_settings_update',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// GET /api/lines/:name/groups/:jid/invite — get group invite link.
export const handleGetGroupInvite = mcpProxy<{ name: string; jid: string }>(
  'get_group_invite_link',
  p => ({ jid: decodeURIComponent(p.jid) }),
);

// POST /api/lines/:name/groups/:jid/invite/revoke — revoke group invite link.
export const handleRevokeGroupInvite = mcpProxy<{ name: string; jid: string }>(
  'group_revoke_invite',
  p => ({ jid: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/ephemeral — toggle ephemeral messages.
export const handleGroupEphemeral = mcpWithBody<{ name: string; jid: string }>(
  'group_toggle_ephemeral',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/member-add-mode — set who can add members.
export const handleGroupMemberAddMode = mcpWithBody<{ name: string; jid: string }>(
  'group_member_add_mode',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// PUT /api/lines/:name/groups/:jid/join-approval — set join approval mode.
export const handleGroupJoinApproval = mcpWithBody<{ name: string; jid: string }>(
  'group_join_approval_mode',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// GET /api/lines/:name/groups/:jid/requests — list pending join requests.
export const handleGetGroupRequests = mcpProxy<{ name: string; jid: string }>(
  'group_request_participants_list',
  p => ({ jid: decodeURIComponent(p.jid) }),
);

// POST /api/lines/:name/groups/:jid/requests — approve/reject join requests.
export const handleGroupRequestsUpdate = mcpWithBody<{ name: string; jid: string }>(
  'group_request_participants_update',
  (b, p) => ({ ...b, jid: decodeURIComponent(p.jid) }),
);

// ---------------------------------------------------------------------------
// Contact search
// ---------------------------------------------------------------------------

/** GET /api/lines/:name/contacts/search?q= — search contacts via MCP. */
export async function handleSearchContacts(
  req: IncomingMessage,
  res: ServerResponse,
  deps: McpProxyDeps,
  params: { name: string },
): Promise<void> {
  const instance = requireInstance(deps.discovery, params.name, res);
  if (!instance) return;

  const qs = parseQueryString(req.url);
  const query = qs.q;
  if (!query) {
    jsonResponse(res, 400, { error: 'q query parameter is required' });
    return;
  }

  if (!socketCheck(instance, res)) return;

  const result = await mcpCall(instance.socketPath!, 'search_contacts', { query });
  if (result.success) {
    // search_contacts returns {results, total} — normalize to {contacts} for console
    const unwrapped = unwrapMcpResult(result.result);
    const contacts = isJsonObject(unwrapped) ? (unwrapped.results ?? unwrapped.contacts ?? unwrapped) : unwrapped;
    jsonResponse(res, 200, { contacts: Array.isArray(contacts) ? contacts : [] });
  }
  else jsonResponse(res, 502, { error: result.error ?? 'MCP call failed' });
}
