export const FITNESS_CATEGORIES = [
  'architecture',
  'invariant',
  'process',
  'hygiene',
  'test',
  'meta',
] as const;

export const DETECTABILITIES = ['mechanical', 'ast', 'semantic', 'human'] as const;
export const FITNESS_RINGS = ['hook', 'eslint', 'guard', 'ci', 'sdlc'] as const;
export const FITNESS_SEVERITIES = ['block', 'warn', 'advisory'] as const;

export type RuleCategory = typeof FITNESS_CATEGORIES[number];
export type Detectability = typeof DETECTABILITIES[number];
export type Ring = typeof FITNESS_RINGS[number];
export type Severity = typeof FITNESS_SEVERITIES[number];

export interface FitnessRule {
  id: string;
  title: string;
  category: RuleCategory;
  rationale: string;
  detect: Detectability;
  rings: Ring[];
  severity: Severity;
  ratchet?: boolean;
  params?: Record<string, unknown>;
  source: string[];
}

export const fitnessRules = [
  {
    id: 'arch.file-size',
    title: 'File size ratchet',
    category: 'architecture',
    rationale: 'Large files concentrate unrelated behavior and should not grow beyond an explicit baseline.',
    detect: 'mechanical',
    rings: ['hook', 'eslint', 'guard', 'ci'],
    severity: 'block',
    ratchet: true,
    params: { maxLines: 2000 },
    source: ['retrospective:runtime.ts-6009-lines', 'retrospective:runtime-test-churn'],
  },
  {
    id: 'arch.god-class',
    title: 'God class warning',
    category: 'architecture',
    rationale: 'A single class owning poll, turn sequencing, gate, compact, and persistence behavior hides invariants.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    params: { maxClassLines: 1200, maxMethods: 80 },
    source: ['retrospective:AgentRuntime-mixed-responsibilities'],
  },
  {
    id: 'arch.test-colocation-churn',
    title: 'Test colocation churn',
    category: 'architecture',
    rationale: 'A test file with churn far above peer files signals an unstable unit boundary.',
    detect: 'mechanical',
    rings: ['guard'],
    severity: 'advisory',
    params: { commitsPerWindow: 10, days: 8 },
    source: ['retrospective:runtime.test.ts-20-commits'],
  },
  {
    id: 'arch.defense-both-layers',
    title: 'Defense at service and route layers',
    category: 'architecture',
    rationale: 'A service-layer guard is incomplete if the route or caller does not thread the required context.',
    detect: 'semantic',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['feedback:service_route_boundary'],
  },
  {
    id: 'arch.import-boundaries',
    title: 'Import boundary ring rule',
    category: 'architecture',
    rationale: 'Import direction between src layers is an architectural invariant; uncontrolled cross-layer reach couples modules and defeats abstraction boundaries.',
    detect: 'mechanical',
    rings: ['guard', 'ci'],
    severity: 'block',
    ratchet: true,
    params: {
      // Importer layer → allowed target layers. Same-layer imports are always
      // permitted by the checker itself; the self-entries here are
      // documentation only, not enforcement.
      layers: {
        lib: ['lib'],
        core: ['core', 'lib'],
        transport: ['transport', 'core', 'lib'],
        mcp: ['mcp', 'core', 'lib', 'transport'],
        runtimes: ['runtimes', 'core', 'lib', 'mcp', 'transport'],
        fleet: ['fleet', 'core', 'lib', 'mcp', 'transport', 'runtimes'],
        memory: ['memory', 'core', 'lib'],
        root: ['*'],
      },
      anyMayImportRoot: true,
    },
    source: ['docs:duplicates-report.md', 'architecture:CLAUDE.md'],
  },
  {
    id: 'invariant.seq-locality',
    title: 'Sequence invariant locality',
    category: 'invariant',
    rationale: 'User inbound sequence and system-turn result counters must be owned by one local abstraction.',
    detect: 'mechanical',
    rings: ['guard'],
    severity: 'warn',
    params: { ownerModule: 'src/runtimes/agent' },
    source: ['commit:a150f7e8', 'commit:fb780bbd', 'retrospective:recurring-seq-bug'],
  },
  {
    id: 'invariant.fail-closed-scanner',
    title: 'Scanners fail closed',
    category: 'invariant',
    rationale: 'Scanner parse or read failures must surface as findings instead of silently returning no issues.',
    detect: 'ast',
    rings: ['eslint', 'sdlc'],
    severity: 'warn',
    source: ['feedback:audit_scanners_fail_closed'],
  },
  {
    id: 'invariant.timer-rearm-without-clear',
    title: 'Inline timer in Map.set re-armed without clear',
    category: 'invariant',
    rationale:
      'Forward-looking guard: writing a timer handle INLINE in a Map.set value literal (map.set(key, { t: setTimeout(...) })) and re-arming the key without first clearing the previous entry orphans the old timer. Catches only the inline shape, which the build-then-set codebase does not currently use (zero findings today); the field-assigned OperationTracker.onToolStart variant is covered by its regression test, not this lexical rule.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    source: ['feedback:operation_tracker_timer_rearm_leak'],
  },
  {
    id: 'invariant.outbox-env-gated',
    title: 'Bot-errors outbox writes go through the env-aware resolver',
    category: 'invariant',
    rationale:
      'A write to the bot-errors outbox via a hardcoded path literal bypasses resolveBotErrorsOutbox() and lands in the PROD outbox even under VITEST/NODE_ENV=test. Outbox writes must derive their path from the resolver so the test-redirect applies.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    source: ['audit:detector-misconceptions#alert-emitter-not-env-gated', 'feedback:dry_run_purity_run_level_test'],
  },
  {
    id: 'invariant.fail-closed-gate',
    title: 'Shell gates fail closed',
    category: 'invariant',
    rationale: 'Readiness and health gates must not mask command failures with sentinel success output.',
    detect: 'mechanical',
    rings: ['guard', 'hook'],
    severity: 'block',
    source: ['feedback:writing_fail_closed_gates', 'feedback:shell_exit_via_pipe'],
  },
  {
    id: 'process.fix-cluster',
    title: 'Fix cluster escalation',
    category: 'process',
    rationale: 'Several fixes to one subsystem in a short window should require a design note before more patches.',
    detect: 'mechanical',
    rings: ['ci'],
    severity: 'advisory',
    params: { fixCommits: 3, days: 7 },
    source: ['prs:704-709', 'retrospective:fix-cluster'],
  },
  {
    id: 'process.canary-before-fleet',
    title: 'Canary before fleet rollout',
    category: 'process',
    rationale: 'Timing-dependent features need single-host canary evidence before fleet-wide enablement.',
    detect: 'human',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['incident:auto-compact-slow-response'],
  },
  {
    id: 'process.deploy-sha-drift',
    title: 'Deployment SHA drift',
    category: 'process',
    rationale: 'Live hosts drifting behind origin/main hide whether fixes are actually deployed.',
    detect: 'mechanical',
    rings: ['guard'],
    severity: 'advisory',
    params: { maxBehindCommits: 0 },
    source: ['audit:anabot-10-commits-behind', 'feedback:dm_runtime_worktree_skew'],
  },
  {
    id: 'process.no-destructive-git',
    title: 'No destructive git commands',
    category: 'process',
    rationale: 'Committed scripts and hooks must not use destructive git cleanup commands.',
    detect: 'mechanical',
    rings: ['guard', 'hook'],
    severity: 'block',
    source: ['feedback:no_git_clean', 'developer-instructions:git-safety'],
  },
  {
    id: 'process.verify-before-claim',
    title: 'Verify before completion claims',
    category: 'process',
    rationale: 'Completion claims need fresh evidence from source control, CI, or runtime checks.',
    detect: 'human',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['feedback:pr_landing_check', 'feedback:agent_commit_verification'],
  },
  {
    id: 'process.evidence-sha-anchor',
    title: 'Evidence SHA anchoring',
    category: 'process',
    rationale: 'Evidence that cites a commit must match the reviewed or published SHA.',
    detect: 'mechanical',
    rings: ['guard'],
    severity: 'warn',
    source: ['feedback:evidence_sha_anchoring'],
  },
  {
    id: 'process.shared-checkout-safety',
    title: 'Shared checkout safety',
    category: 'process',
    rationale: 'Agents must not clean, switch, or commit over another session in a shared checkout.',
    detect: 'human',
    rings: ['hook', 'sdlc'],
    severity: 'advisory',
    source: ['feedback:shared_checkout_multi_agent', 'feedback:worktree_state_safety'],
  },
  {
    id: 'hygiene.commit-author',
    title: 'Canonical commit author',
    category: 'hygiene',
    rationale: 'Placeholder or tool-generated author identities must not enter public history.',
    detect: 'mechanical',
    rings: ['guard', 'ci'],
    severity: 'block',
    params: { allowedIdentityRefs: ['canonical-local-author', 'github-noreply-author'] },
    source: ['audit:whatsoup-test-invalid-history'],
  },
  {
    id: 'hygiene.internal-labels',
    title: 'Internal label hygiene',
    category: 'hygiene',
    rationale: 'Public repo content must not leak internal planning labels or private workstream names.',
    detect: 'mechanical',
    rings: ['guard'],
    severity: 'block',
    source: ['feedback:hygiene_internal_labels', 'existing:repo-hygiene-guard'],
  },
  {
    id: 'hygiene.pr-scope-coherence',
    title: 'PR scope coherence',
    category: 'hygiene',
    rationale: 'PR title type should match diff scope so broad systems do not hide inside narrow labels.',
    detect: 'semantic',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['feedback:pr_scope_title_coherence'],
  },
  {
    id: 'test.typecheck-all-required',
    title: 'Full typecheck required',
    category: 'test',
    rationale: 'Local push and CI paths must typecheck tests with tsconfig.test.json, not only source files.',
    detect: 'mechanical',
    rings: ['guard', 'ci'],
    severity: 'block',
    source: ['feedback:test_author_typecheck_all', 'audit:verify-push-branch-typecheck-gap'],
  },
  {
    id: 'test.skip-categorization',
    title: 'Categorized skips',
    category: 'test',
    rationale: 'Environment-dependent skips and timing-dependent skips need different handling and evidence.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'advisory',
    source: ['feedback:skip_categorization', 'feedback:masked_test_signal'],
  },
  {
    id: 'test.red-green-required',
    title: 'Red-green proof',
    category: 'test',
    rationale: 'A fix should include a test that would fail before the change, not only characterize fragile behavior.',
    detect: 'semantic',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['retrospective:characterization-tests', 'feedback:verification_before_completion'],
  },
  {
    id: 'meta.no-redundant-gates',
    title: 'No redundant gates',
    category: 'meta',
    rationale: 'New enforcement should feed existing guards and agents rather than adding parallel L1 checks.',
    detect: 'human',
    rings: ['sdlc'],
    severity: 'advisory',
    source: ['feedback:l1_pipeline_weight'],
  },
  {
    id: 'arch.approved-api-client',
    title: 'Console network requests through approved API client',
    category: 'architecture',
    rationale: 'Direct fetch calls in console UI bypass auth-ticket handling, timeouts, response parsing, and the test surface that agents preserve.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    source: ['architecture:console-api-client'],
  },
  {
    id: 'arch.ring-boundaries',
    title: 'Backend ring boundary enforcement',
    category: 'architecture',
    rationale: 'Lower architectural rings must not import higher rings; coupling direction is an architectural invariant for autonomous agent reliability.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    source: ['architecture:ring-boundaries'],
  },
  {
    id: 'invariant.no-unsafe-type-escapes',
    title: 'No unsafe TypeScript type escapes in production code',
    category: 'invariant',
    rationale: 'any and TypeScript suppressions erase compiler feedback that autonomous agents depend on as operating boundaries.',
    detect: 'ast',
    rings: ['eslint'],
    severity: 'warn',
    source: ['feedback:feedback_runner_api_verification'],
  },
  {
    id: 'test.insecure-tempfile',
    title: 'No insecure temp-file creation in python or shell',
    category: 'test',
    rationale:
      'tempfile.mktemp() and hardcoded /tmp write-targets create predictable paths (TOCTOU race, cross-user readable). Fixed repo-wide; this rule blocks regression. Detects creation/write only, not read-only references. f-string /tmp write-targets are covered; os.path.join/shutil/os.open /tmp write-targets are a known detector gap (dataflow analysis required to avoid false positives).',
    detect: 'mechanical',
    rings: ['guard', 'ci'],
    severity: 'block',
    source: ['codeql:py/insecure-temporary-file', 'spec:2026-06-27-insecure-tempfile'],
  },
] satisfies FitnessRule[];
