#!/usr/bin/env node
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { pathToFileURL } from 'node:url';

import { defaultSettingsJson } from '../src/core/settings-template.ts';

export interface ParsedArgs {
  mode: 'check' | 'write';
  help: boolean;
}

export interface ClaudeSettingsGuardResult {
  settingsPath: string;
  expected: string;
  actual: string | null;
  ok: boolean;
  written: boolean;
}

const defaultSettingsPath = '.claude/settings.json';

export function parseArgs(argv: string[]): ParsedArgs {
  const args: ParsedArgs = { mode: 'check', help: false };

  for (const arg of argv) {
    if (arg === '--help' || arg === '-h') {
      args.help = true;
    } else if (arg === '--check') {
      args.mode = 'check';
    } else if (arg === '--write') {
      args.mode = 'write';
    } else {
      throw new Error(`Unknown argument: ${arg}`);
    }
  }

  return args;
}

export function renderExpectedClaudeSettings(): string {
  const settings = defaultSettingsJson('agent');
  if (!settings) {
    throw new Error('defaultSettingsJson("agent") returned null');
  }
  return `${JSON.stringify(settings, null, 2)}\n`;
}

function settingsPathFor(cwd: string): string {
  return path.join(cwd, defaultSettingsPath);
}

export function checkClaudeSettings(cwd = process.cwd()): ClaudeSettingsGuardResult {
  const settingsPath = settingsPathFor(cwd);
  const expected = renderExpectedClaudeSettings();
  const actual = existsSync(settingsPath) ? readFileSync(settingsPath, 'utf8') : null;
  return {
    settingsPath,
    expected,
    actual,
    ok: actual === expected,
    written: false,
  };
}

export function writeClaudeSettings(cwd = process.cwd()): ClaudeSettingsGuardResult {
  const settingsPath = settingsPathFor(cwd);
  const expected = renderExpectedClaudeSettings();
  mkdirSync(path.dirname(settingsPath), { recursive: true });
  writeFileSync(settingsPath, expected, 'utf8');
  return {
    settingsPath,
    expected,
    actual: expected,
    ok: true,
    written: true,
  };
}

function printHelp(): void {
  console.log(`Usage: npm run guard:claude-settings -- [--check|--write]

Verifies that .claude/settings.json matches the agent default generated by
src/core/settings-template.ts. Use --write to regenerate the checked artifact.`);
}

function printDrift(result: ClaudeSettingsGuardResult): void {
  const actualLength = result.actual === null ? 0 : result.actual.length;
  console.error(
    `.claude/settings.json drift detected at ${result.settingsPath}`,
  );
  console.error(
    `  expected ${result.expected.length} bytes from defaultSettingsJson("agent"), found ${actualLength} bytes`,
  );
  console.error(
    '  run: npm run guard:claude-settings -- --write',
  );
}

export function run(
  argv: string[] = process.argv.slice(2),
  cwd = process.cwd(),
): ClaudeSettingsGuardResult {
  const args = parseArgs(argv);
  if (args.help) {
    printHelp();
    return {
      settingsPath: settingsPathFor(cwd),
      expected: '',
      actual: null,
      ok: true,
      written: false,
    };
  }

  if (args.mode === 'write') {
    const result = writeClaudeSettings(cwd);
    console.log(`claude-settings guard wrote ${defaultSettingsPath}`);
    return result;
  }

  const result = checkClaudeSettings(cwd);
  if (!result.ok) {
    printDrift(result);
    process.exitCode = 1;
  } else {
    console.log('claude-settings guard passed');
  }
  return result;
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  try {
    run();
  } catch (err) {
    console.error((err as Error).message);
    process.exitCode = 1;
  }
}
