import { mkdtempSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { describe, expect, it } from 'vitest';

import {
  parseAdoptPrint,
  resolveArcRepoDir,
  checkArcBindingDrift,
  checkVendoredSha,
  extractSha,
} from '../../scripts/arc-binding-drift-check.ts';

const TOML_A85E = [
  '# GENERATED by arc adopt. Do not hand-edit.',
  'arc_version = "0.1.0"',
  'consumer = "whatsoup"',
  'emits = []',
  '',
  '[source]',
  'payload_sha = "sha256:a85e"',
  'generated_by = "arc adopt"',
].join('\n');

const MD_A85E = [
  '<!-- GENERATED by arc adopt. Do not hand-edit. -->',
  '# ARC Binding: whatsoup',
  '',
  '- Payload SHA: `sha256:a85e`',
  '- Emits: none',
].join('\n');

const TOML_4FEF = TOML_A85E.replace('a85e', '4fef').replace(
  'emits = []',
  'emits = ["fallback-event"]',
);

/** Write a stub adopt.py that prints the two given files in adopt --print format. */
function makeArcRepo(toml: string, md: string): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'arc-repo-'));
  mkdirSync(path.join(dir, 'tools'), { recursive: true });
  const stub = [
    'import sys',
    `print("----- arc.toml -----")`,
    `sys.stdout.write(${JSON.stringify(toml)} + "\\n")`,
    `print("----- ARC_BINDING.md -----")`,
    `sys.stdout.write(${JSON.stringify(md)} + "\\n")`,
  ].join('\n');
  writeFileSync(path.join(dir, 'tools', 'adopt.py'), stub);
  return dir;
}

/**
 * Write a repo root with tracked .arc/ files. By default the vendored
 * `.arc/.canonical-sha` pin is derived from the `arc.toml` sha so the pin check
 * agrees; pass `pinSha` to force a mismatching (stale) pin.
 */
function makeRepoRoot(
  toml: string,
  md: string,
  opts: { pinSha?: string; writePin?: boolean } = {},
): string {
  const dir = mkdtempSync(path.join(tmpdir(), 'arc-consumer-'));
  mkdirSync(path.join(dir, '.arc'), { recursive: true });
  writeFileSync(path.join(dir, '.arc', 'arc.toml'), `${toml}\n`);
  writeFileSync(path.join(dir, '.arc', 'ARC_BINDING.md'), `${md}\n`);
  const writePin = opts.writePin ?? true;
  if (writePin) {
    const pinSha = opts.pinSha ?? extractSha(toml) ?? 'sha256:a85e';
    writeFileSync(path.join(dir, '.arc', '.canonical-sha'), `${pinSha}\n`);
  }
  return dir;
}

describe('parseAdoptPrint', () => {
  it('splits the banner-delimited sections', () => {
    const out = `----- arc.toml -----\n${TOML_A85E}\n----- ARC_BINDING.md -----\n${MD_A85E}\n`;
    const parsed = parseAdoptPrint(out);
    expect(parsed['arc.toml'].trimEnd()).toBe(TOML_A85E);
    expect(parsed['ARC_BINDING.md'].trimEnd()).toBe(MD_A85E);
  });
});

describe('resolveArcRepoDir', () => {
  it('prefers ARC_REPO_DIR when it has tools/adopt.py', () => {
    const arc = makeArcRepo(TOML_A85E, MD_A85E);
    expect(resolveArcRepoDir('/nonexistent/repo', { ARC_REPO_DIR: arc })).toBe(
      arc,
    );
  });

  it('returns undefined when no candidate has adopt.py', () => {
    const empty = mkdtempSync(path.join(tmpdir(), 'arc-empty-'));
    expect(resolveArcRepoDir(empty, {})).toBeUndefined();
  });
});

describe('extractSha', () => {
  it('pulls the sha token from a raw pin line', () => {
    expect(extractSha('sha256:a85e\n')).toBe('sha256:a85e');
  });
  it('pulls the sha token from a toml payload_sha line', () => {
    expect(extractSha('payload_sha = "sha256:a85e"')).toBe('sha256:a85e');
  });
  it('pulls the sha token from an ARC_BINDING.md Payload SHA line', () => {
    expect(extractSha('- Payload SHA: `sha256:a85e`')).toBe('sha256:a85e');
  });
  it('returns undefined when no sha token is present', () => {
    expect(extractSha('emits = []')).toBeUndefined();
  });
});

describe('checkVendoredSha', () => {
  it('passes when pin, arc.toml, and ARC_BINDING.md all agree (no sibling repo needed)', () => {
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E);
    expect(checkVendoredSha({ repoRoot }).status).toBe('ok');
  });

  it('detects drift when arc.toml is stale vs the pin (the #1274-in-CI case)', () => {
    // arc.toml/md say 4fef but the committed pin still says a85e.
    const repoRoot = makeRepoRoot(
      TOML_4FEF,
      MD_A85E.replace('a85e', '4fef'),
      { pinSha: 'sha256:a85e' },
    );
    const result = checkVendoredSha({ repoRoot });
    expect(result.status).toBe('drift');
    expect(result.pinDrift?.join('\n')).toContain('sha256:4fef');
    expect(result.pinDrift?.join('\n')).toContain('vendored pin sha256:a85e');
  });

  it('detects drift when the vendored pin is missing entirely', () => {
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E, { writePin: false });
    const result = checkVendoredSha({ repoRoot });
    expect(result.status).toBe('drift');
    expect(result.pinDrift?.join('\n')).toContain('.canonical-sha');
  });
});

describe('checkArcBindingDrift', () => {
  it('runs the vendored-pin check and passes when .arc/ agrees, with no sibling repo (CI mode)', () => {
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E);
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir: undefined });
    expect(result.status).toBe('ok');
  });

  it('HARD-BLOCKS a stale .arc/ in CI mode (no sibling repo) via the vendored pin', () => {
    // The #1274-in-CI regression: arc.toml went stale (4fef) but the pin is a85e,
    // and the sibling repo is absent. Previously this SKIPped and merged green.
    const repoRoot = makeRepoRoot(
      TOML_4FEF,
      MD_A85E.replace('a85e', '4fef'),
      { pinSha: 'sha256:a85e' },
    );
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir: undefined });
    expect(result.status).toBe('drift');
    expect(result.pinDrift?.join('\n')).toContain('sha256:4fef');
  });

  it('still runs the vendored-pin check when adopt.py is missing from the given ARC repo', () => {
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E);
    const emptyArc = mkdtempSync(path.join(tmpdir(), 'arc-noadopt-'));
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir: emptyArc });
    expect(result.status).toBe('ok');
  });

  it('cross-checks the vendored pin against the live generator and reports drift when the pin is stale', () => {
    // .arc/ and pin all agree on a85e locally, but the live generator now emits
    // 4fef — the pin itself is stale and must be updated.
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E, { pinSha: 'sha256:a85e' });
    const arcRepoDir = makeArcRepo(TOML_4FEF, MD_A85E.replace('a85e', '4fef'));
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir });
    expect(result.status).toBe('drift');
    expect(result.pinDrift?.join('\n')).toContain('update .arc/.canonical-sha');
  });

  it('passes when tracked .arc/ matches the canonical generator output', () => {
    const repoRoot = makeRepoRoot(TOML_A85E, MD_A85E);
    const arcRepoDir = makeArcRepo(TOML_A85E, MD_A85E);
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir });
    expect(result.status).toBe('ok');
  });

  it('detects drift when tracked .arc/ is stale (the #1274 class)', () => {
    const repoRoot = makeRepoRoot(TOML_4FEF, MD_A85E.replace('a85e', '4fef'));
    const arcRepoDir = makeArcRepo(TOML_A85E, MD_A85E);
    const result = checkArcBindingDrift({ repoRoot, arcRepoDir });
    expect(result.status).toBe('drift');
    expect(result.driftedFiles).toEqual([
      {
        file: '.arc/arc.toml',
        trackedShaLine: 'payload_sha = "sha256:4fef"',
        canonicalShaLine: 'payload_sha = "sha256:a85e"',
      },
      {
        file: '.arc/ARC_BINDING.md',
        trackedShaLine: '- Payload SHA: `sha256:4fef`',
        canonicalShaLine: '- Payload SHA: `sha256:a85e`',
      },
    ]);
  });
});
