import { randomUUID } from 'node:crypto';
import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { afterEach, describe, expect, it, vi } from 'vitest';

import { run } from '../../scripts/arc-runtime-proof.ts';

const SHA_A = `sha256:${'a'.repeat(64)}`;
const SHA_B = `sha256:${'b'.repeat(64)}`;
const tempRoots: string[] = [];

function makeRoot(): string {
  const root = path.join(tmpdir(), `whatsoup-arc-proof-${randomUUID()}`);
  mkdirSync(path.join(root, '.arc'), { recursive: true });
  tempRoots.push(root);
  return root;
}

function arcToml(opts: { emits: string[]; payloadSha?: string }): string {
  const emits = opts.emits.map((entry) => `"${entry}"`).join(', ');
  return [
    '# GENERATED by arc adopt. Do not hand-edit; edit ARC bindings/modules instead.',
    'arc_version = "0.1.0"',
    'consumer = "whatsoup"',
    'modules = ["app-runtime", "telemetry", "verification"]',
    `emits = [${emits}]`,
    '',
    '[source]',
    'binding = "bindings/whatsoup.arc.json"',
    `payload_sha = "${opts.payloadSha ?? SHA_A}"`,
    'generated_by = "arc adopt"',
    '',
  ].join('\n');
}

function arcBindingMd(opts: { emits: string[]; payloadSha?: string }): string {
  const emits = opts.emits.length > 0 ? opts.emits.join(', ') : 'none';
  return [
    '<!-- GENERATED by arc adopt. Do not hand-edit. -->',
    '# ARC Binding: whatsoup',
    '',
    `- Payload SHA: \`${opts.payloadSha ?? SHA_A}\``,
    `- Emits: ${emits}`,
    '',
  ].join('\n');
}

function writeArcFiles(root: string, opts: { emits: string[]; payloadSha?: string }): void {
  const payloadSha = opts.payloadSha ?? SHA_A;
  writeFileSync(path.join(root, '.arc', 'arc.toml'), arcToml({ ...opts, payloadSha }), 'utf8');
  writeFileSync(path.join(root, '.arc', 'ARC_BINDING.md'), arcBindingMd({ ...opts, payloadSha }), 'utf8');
  writeFileSync(path.join(root, '.arc', '.canonical-sha'), `${payloadSha}\n`, 'utf8');
}

function healthJson(root: string, opts: { payloadSha?: string; extra?: Record<string, unknown> } = {}): string {
  const file = path.join(root, 'health.json');
  writeFileSync(file, `${JSON.stringify({
    arc: {
      loaded: true,
      consumer: 'whatsoup',
      arcVersion: '0.1.0',
      modules: ['app-runtime', 'telemetry', 'verification'],
      emits: ['verification-record'],
      binding: 'bindings/whatsoup.arc.json',
      payloadSha: opts.payloadSha ?? SHA_A,
    },
    ...opts.extra,
  }, null, 2)}\n`, 'utf8');
  return file;
}

afterEach(() => {
  vi.restoreAllMocks();
  for (const root of tempRoots.splice(0)) rmSync(root, { recursive: true, force: true });
});

describe('arc-runtime-proof', () => {
  it('refuses to write proof while the installed binding does not declare verification-record emission', () => {
    const root = makeRoot();
    writeArcFiles(root, { emits: [] });
    const out = path.join(root, '.arc', 'runtime-enforcement.verification-record.json');
    const stderr = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const code = run(['--health-json', healthJson(root), '--out', out, '--repo-root', root], root);

    expect(code).toBe(1);
    expect(existsSync(out)).toBe(false);
    expect(stderr).toHaveBeenCalledWith(expect.stringContaining('verification-record'));
  });

  it('writes a verification-record proof containing runtime-health evidence when runtime health and installed binding agree', () => {
    const root = makeRoot();
    writeArcFiles(root, { emits: ['verification-record'] });
    const out = path.join(root, '.arc', 'runtime-enforcement.verification-record.json');

    const code = run(['--health-json', healthJson(root), '--out', out, '--repo-root', root], root);

    expect(code).toBe(0);
    expect(existsSync(out)).toBe(true);
    const written = JSON.parse(readFileSync(out, 'utf8')) as Record<string, unknown>;
    expect(written).toMatchObject({
      proof_class: 'probe',
      source_layer: 'judgment',
      payload_type: 'verification-record',
      payload: {
        claim: 'whatsoup runtime loaded and enforced ARC binding',
        verdict: 'pass',
        evidence_refs: [
          'arc-binding:whatsoup',
          'install-target:whatsoup',
          'runtime-health:whatsoup',
        ],
      },
    });
  });

  it('refuses when runtime health payloadSha disagrees with the installed binding', () => {
    const root = makeRoot();
    writeArcFiles(root, { emits: ['verification-record'], payloadSha: SHA_A });
    const out = path.join(root, '.arc', 'runtime-enforcement.verification-record.json');
    const stderr = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const code = run(['--health-json', healthJson(root, { payloadSha: SHA_B }), '--out', out, '--repo-root', root], root);

    expect(code).toBe(1);
    expect(existsSync(out)).toBe(false);
    expect(stderr).toHaveBeenCalledWith(expect.stringContaining('payloadSha'));
  });

  it('refuses secret-like health JSON before writing proof', () => {
    const root = makeRoot();
    writeArcFiles(root, { emits: ['verification-record'] });
    const out = path.join(root, '.arc', 'runtime-enforcement.verification-record.json');
    const secretLike = ['API_', 'TOKEN=', 'secret-material-', '1234567890'].join('');
    const stderr = vi.spyOn(console, 'error').mockImplementation(() => undefined);

    const code = run([
      '--health-json',
      healthJson(root, { extra: { diagnostic: secretLike } }),
      '--out',
      out,
      '--repo-root',
      root,
    ], root);

    expect(code).toBe(1);
    expect(existsSync(out)).toBe(false);
    expect(stderr).toHaveBeenCalledWith(expect.stringContaining('redaction_violation'));
  });
});
